Repository wanted-wecode-subjects/eight-percent-subject, pull requests merged in 2021-11, with the labels that each got.

#18 chore: .eslintrc rules 변경
  .eslintrc.js
Labels: chore

#19 feat: core entity 구현
  src/core/entities/core.entity.ts
Labels: feat

#22 feat: accounts 모듈 초기 설정
  package-lock.json
  package.json
  src/accounts/accounts.controller.ts
  src/accounts/accounts.module.ts
  src/accounts/accounts.repository.ts
  src/accounts/accounts.service.ts
  src/accounts/dto/create-account.dto.ts
  src/accounts/dto/update-account.dto.ts
  src/accounts/entities/account.entity.ts
  src/app.module.ts
Labels: feat

#23 feat : 유저 기본 세팅 & 회원 가입
  src/app.module.ts
  src/users/dto/create-user.dto.ts
  src/users/entities/user.entity.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: feat

#24 feat: account create
  package-lock.json
  src/accounts/accounts.controller.ts
  src/accounts/accounts.service.ts
  src/accounts/dto/create-account.dto.ts
  src/accounts/entities/account.entity.ts
Labels: feat

#26 feat: account find
  src/accounts/accounts.controller.ts
  src/accounts/accounts.service.ts
Labels: feat

#29 feat: 로그인
  src/app.module.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/users/dto/signin.dto.ts
  src/users/users.controller.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: feat

#25 feat:transaction기본설정
  src/app.module.ts
  src/transaction/dto/create-transaction.dto.ts
  src/transaction/entities/transaction.entity.ts
  src/transaction/transaction.controller.spec.ts
  src/transaction/transaction.controller.ts
  src/transaction/transaction.module.ts
  src/transaction/transaction.service.spec.ts
  src/transaction/transaction.service.ts
Labels: feat

#28 feat: account update
  src/accounts/accounts.controller.ts
  src/accounts/accounts.service.ts
  src/accounts/dto/update-account.dto.ts
Labels: feat

#31 feat: 유저 가드, 데코레이터
  src/auth/auth-guard/jwt-auth.guard.ts
  src/auth/auth.module.ts
  src/auth/auth.service.ts
  src/auth/get-user.decorator.ts
  src/auth/strategies/jwt.strategy.ts
  src/users/entities/user.entity.ts
  src/users/users.module.ts
  src/users/users.service.ts
Labels: feat

#35 feat: account guard
  src/accounts/accounts.controller.ts
  src/accounts/entities/account.entity.ts
  src/users/entities/user.entity.ts
Labels: feat

#32 feat: account create 중복 체크 구현
  src/accounts/accounts.service.ts
Labels: feat

#36 feat : jwt strategy id 추가
  src/auth/auth.service.ts
  src/auth/strategies/jwt.strategy.ts
Labels: feat

#38 feat: account create getuser적용
  src/accounts/accounts.controller.ts
  src/accounts/accounts.service.ts
Labels: feat

#39 feat: 계좌 소유주 확인
  src/accounts/accounts.controller.ts
  src/accounts/accounts.module.ts
  src/accounts/accounts.service.ts
Labels: feat

#43 feat: 계좌번호로 계좌 조회
  src/accounts/accounts.repository.ts
  src/accounts/accounts.service.ts
Labels: feat

#44 feat : 로그아웃
  src/users/users.controller.ts
  src/users/users.service.ts
Labels: feat

#41 feat:입금 기능 추가
  src/accounts/entities/account.entity.ts
  src/app.module.ts
  src/transaction/dto/create-transaction.dto.ts
  src/transaction/entities/transaction.entity.ts
  src/transaction/transaction.controller.ts
  src/transaction/transaction.module.ts
  src/transaction/transaction.repository.ts
  src/transaction/transaction.service.ts
Labels: feat

#48 feat:출금기능 추가
  src/transaction/transaction.controller.ts
  src/transaction/transaction.repository.ts
  src/transaction/transaction.service.ts
Labels: feat

#47 feat: 거래내역 목록 조회
  package-lock.json
  package.json
  src/accounts/entities/account.entity.ts
  src/transaction/dto/create-transaction.dto.ts
  src/transaction/entities/transaction.entity.ts
  src/transaction/transaction.controller.ts
  src/transaction/transaction.interface.ts
  src/transaction/transaction.module.ts
  src/transaction/transaction.repository.ts
  src/transaction/transaction.service.ts
Labels: feat

#50 test: account controller test
  src/accounts/accounts.controller.spec.ts
Labels: test

#49 test: account service test
  src/accounts/accounts.repository.spec.ts
  src/accounts/accounts.service.spec.ts
Labels: test

#52 fix/develop 브랜치 내 코드 중복 수정
  src/accounts/entities/account.entity.ts
  src/transaction/dto/create-transaction.dto.ts
Labels: bug, fix

#55 test: user test
  src/users/users.controller.spec.ts
  src/users/users.service.spec.ts
Labels: test

#56 test: auth service test
  src/auth/auth.service.spec.ts
Labels: test

#63 fix: transaction get
  src/transaction/transaction.interface.ts
  src/transaction/transaction.repository.ts
  src/transaction/transaction.service.ts
Labels: fix

#61 test: 거래내역 컨트롤러 테스트
  src/transaction/transaction.controller.spec.ts
  src/transaction/transaction.service.spec.ts
Labels: test

#65 feat: Transaction 테이블 인덱싱 추가
  src/transaction/entities/transaction.entity.ts
Labels: feat
